version: 2.1

workflows:
  say-hello-workflow:
    jobs:
      - print_hello 

jobs:
  print_hello:
    docker:
      - image: cimg/base:2020.01
    environment:
      TempVariable: My pipeline id is << pipeline.id >>,pipeline number is <<pipeline.number>>,project git_url is <<pipeline.project.git_url>>,commit refernece is ${CIRCLE_SHA1} and my git branch is << pipeline.git.branch >> 
    steps:
      - run: echo $TempVariable
      - run:
          name: "echo an env var that is part of our project"
          command: |
            echo $JSB_ENV_VAR2      

  save_hello_world_output:
      docker:
        - image: cimg/base:2020.01
      steps:
        - run: echo "text to output here" > output.txt
        - persist_to_workspace:
            root: /tmp/workspace
            paths: output.txt

  print_output_file:
      docker:
        - image: cimg/base:2020.01
      steps:
        - attach_workspace:
            at: /tmp/workspace
        - run: echo "Getting the contents of the file output.txt"            
        - run: cat output.txt 