version: 2.1

jobs:

  print_hello:
    docker:
      - image: circleci/node:13.8.0

    environment:
      TempVariable: My pipeline id is << pipeline.id >>,pipeline number is <<pipeline.number>>,project git_url is <<pipeline.project.git_url>>,commit refernece is ${CIRCLE_SHA1} and my git branch is << pipeline.git.branch >> 

    steps:
      - run: echo $TempVariable

  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo Welcome Mr.${JSB_ENV_VAR2}

workflows:
  say-hello-workflow:
    jobs:
      - print_hello
      - print_world:
          requires:
            - print_hello      
