version: 2.1

jobs:

  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo "My pipeline id is << pipeline.id >>,pipeline number is <<pipeline.number>>,project git_url is <<pipeline.project.git_url>> and my git branch is << pipeline.git.branch >>"

  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          command: "echo world"      

workflows:
  say-hello-workflow:
    jobs:
      - print_hello
      - print_world:
          requires:
            - print_hello      
