defaults: &defaults
  docker:
    - image: cimg/base:2020.01

version: 2.1

workflows:
  say-hello-workflow:
    jobs:
      - save_hello_world_output
      - print_hello      
      - print_output_file:
          requires:
            - save_hello_world_output
jobs:
  print_hello:
    <<: *defaults
    environment:
      TempVariable: My pipeline id is << pipeline.id >>,pipeline number is <<pipeline.number>>,project git_url is <<pipeline.project.git_url>>,commit refernece is ${CIRCLE_SHA1} and my git branch is << pipeline.git.branch >> 
    steps:
      - run: echo $TempVariable
      - run:
          name: "echo an env var that is part of our projects"
          command: |
            echo $JSB_ENV_VAR2      

  save_hello_world_output:
    <<: *defaults
    steps:
      - run: echo "text to output here" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths: output.txt

  print_output_file:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: echo "Getting the contents of the file output.txt"            
      - run: cat ~/output.txt